# Generated by Django 3.0.2 on 2020-10-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('per_Details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ename_f',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ename_l',
            field=models.CharField(max_length=50),
        ),
    ]
