# Generated by Django 3.1.2 on 2020-10-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rprice',
            field=models.CharField(max_length=30),
        ),
    ]
