# Generated by Django 2.2 on 2020-09-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=255)),
                ('lName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=20)),
                ('AccNo', models.IntegerField()),
                ('tariff', models.IntegerField()),
                ('unitMon1', models.IntegerField()),
                ('unitMon2', models.IntegerField()),
                ('unitMon3', models.IntegerField()),
                ('supMon1', models.IntegerField()),
                ('supMon2', models.IntegerField()),
                ('supMon3', models.IntegerField()),
                ('cardNo', models.CharField(max_length=20)),
                ('cardName', models.CharField(max_length=255)),
                ('secCode', models.IntegerField()),
                ('expireDate', models.CharField(max_length=10)),
            ],
        ),
    ]
