# Generated by Django 2.2 on 2020-09-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cusDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusName', models.CharField(max_length=255)),
                ('projDetails', models.CharField(max_length=20000)),
                ('location', models.CharField(max_length=100)),
                ('totPrice', models.FloatField()),
                ('stageOnePrice', models.FloatField()),
                ('stageTwoPrice', models.FloatField()),
                ('stageThreePrice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='cusStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusName', models.CharField(max_length=255)),
                ('projDetails', models.CharField(max_length=20000)),
                ('location', models.CharField(max_length=100)),
                ('totPrice', models.FloatField()),
            ],
        ),
    ]
